name: Deploy Publisher AWS Lambda

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  deploy-publisher:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy Publisher Lambda Function
      run: |
        zip -j publisher-lambda.zip ./publisher/lambda_function.py
        aws s3 cp publisher-lambda.zip s3://srini-prasad-bucket/
        #aws lambda update-function-code \
        #  --function-name PublisherFunction \
        #  --zip-file fileb://publisher-lambda.zip
