name: Deploy Subscriber 2 AWS Lambda

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  deploy-subscriber2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy Subscriber 2 Lambda Function
      run: |
        zip -j subscriber2-lambda.zip ./subscriber2/lambda_function.py
        aws s3 cp subscriber2-lambda.zip s3://srini-prasad-bucket/
        #aws lambda update-function-code \
        #  --function-name Subscriber2Function \
        #  --zip-file fileb://subscriber2-lambda.zip
